### ISSUE TITLE
should recommend choosing a FOSS license

### ISSUE THREAD

**Issue by zacchiro** [fsfe/reuse-docs#1]
REUSE (whose stated mission is "We’re making managing copyrights and licenses in free and open source software easier.") should recommend as a first best practice the adoption of FOSS licenses for distributed software, and it currently does not. The "Practices" page does link to the SPDX license list, but that is not enough to address this issue, as the list contains both free and non-free licenses.

Thanks for REUSE !

**Comment by silverhook** [comment]
Hi @zacchiro, do you consider this fixed by the following two commit?

- https://github.com/fsfe/reuse-docs/commit/1c895a057e72f4cee784d81ba7eee84f4fa68bfb
- https://github.com/fsfe/reuse-docs/commit/0956e35b4726ccb846c518f0f05d0a595287f40a

If not, additional help would be much appreciated.

**Comment by zacchiro** [comment]
@silverhook LGTM. I'd probably anticipate the comment about choosing a Free Software license before everything else, but YMMV.

**Comment by silverhook** [comment]
@zacchiro, I assumed the choosers were promoting FOSS licenses, but that is a good point. Can you suggest some wordin?

**Comment by zacchiro** [comment]
> @zacchiro, I assumed the choosers were promoting FOSS licenses, but that is a good point. Can you suggest some wording?

here it is: #41
