### ISSUE TITLE
Document current precedence of information

### ISSUE THREAD

**Issue by pietroalbini** [fsfe/reuse-docs#111]
REUSE currently looks at multiple sources when deciding what the license of a file should be, but the precedence of those sources is not documented in the specification. This results in people having to experiment on their own to determine what the current precedence is, which is not great. It would be nice if the current precedence would be written in the specification.

I know that in https://github.com/fsfe/reuse-docs/issues/70 there is an insightful discussion on what the precedence of information *should* be, keeping in mind the future `REUSE.yaml` file, but that is orthogonal to documenting the current behavior of the tool.

**Comment by mxmehl** [comment]
Thanks. I agree that we should implement this rather sooner than later, since REUSE.yaml might still be a longer road.
