### ISSUE TITLE
FAQ - Can my BSD-3 license contains two copyright ? 

### ISSUE THREAD

**Issue by StephaneCapponi** [fsfe/reuse-docs#116]
Hi,

I'm working on a project that I want to release under BSD-3 License. The issue that I face is simple. I took and modified some code from another project that is based on the same license (BSD-3). It is specified in the BSD3 License that I should add the copyright. 

Should I put only one file (BSD-3-Clause.txt) in LICENSES with my copyright and the copyright of the owner of some of the code that I have in my project ? Or should I put two BSD-3 Licenses. One with my copyright and the same one with the copyright owner of the code that I modified ?  (BSD-3-Clause.ME.txt - BSD-3-Clause-Other.txt)

Sorry if the question might be stupid but licensing is a nightmare :)

**Comment by mxmehl** [comment]
Sorry for the late reply.

Yes, such template licenses are a nightmare. Strictly speaking, both licenses are separate licenses. We have listed two options here, and it's up to you which route you go: https://reuse.software/faq/#license-templates

IMHO it's already well covered in the FAQ, so I'll close for now. But we can reopen if you think something's missing.

**Comment by StephaneCapponi** [comment]
Hi,

Thanks for your answer. I will follow the FAQ, I didn't see that the answer was in it. I believe it's because I didn't really know what I was searching for. I will follow what it is said
