### ISSUE TITLE
There’s more than one version 3.0 of the REUSE Spec

### ISSUE THREAD

**Issue by Jayman2000** [fsfe/reuse-docs#120]
[The version that’s currently published on reuse.software](https://reuse.software/spec/) says that it’s version 3.0 and contains a definition for Covered File. The Wayback Machine has [a version of that page](https://web.archive.org/web/20191125144427/https://reuse.software/spec/) that says that it’s version 3.0 but doesn’t contain a definition for Covered File.

I would expect the older version to be labeled 3.0, but I would expect the current version to be labeled 3.1 or something.

**Comment by silverhook** [comment]
3.0 is:
https://github.com/fsfe/reuse-docs/tree/v3.0
https://github.com/fsfe/reuse-docs/blob/main/CHANGELOG.md#30---2019-08-07

If the page does not show that, that’s indeed a bug! A non-versioned/non-released state should _not_ be published as the spec on the website.

**Comment by mxmehl** [comment]
IIRC we said that a mere clarification (which I think the Covered File is) does not demand a spec version update. However, I agree that the changelog entry would have been necessary.

We should issue an update soon anyway, e.g. for the snippets support.

**Comment by mxmehl** [comment]
Closing this as we will release 3.1 today.
