### ISSUE TITLE
Spec’s comment header rule isn’t followed or enforced

### ISSUE THREAD

**Issue by Jayman2000** [fsfe/reuse-docs#122]
[Dave Winer’s Rules for standards-makers](http://scripting.com/2017/05/09/rulesForStandardsmakers.html) says “If practice deviates from the spec, change the spec”. If a spec says to do one thing but everyone does something else, then that rule in the spec is more of a distraction then anything else.

The REUSE Spec says “To implement this method, each plain text file that can contain comments MUST contain comments at the top of the file (comment header) that declare that file’s Copyright and Licensing Information.” As far as I know, there’s no piece of software that actually enforces that requirement.

Try running `reuse lint` on [this repository](https://github.com/Jayman2000/reuse-compliance-test). The REUSE Tool will tell you that you’re compliant with the REUSE Spec, even though there’s a `.py.license` file (The Python file itself could have just contained a comment header).

The requirement should be changed to match the way people actually implement REUSE. The word “MUST” should be changed to “SHOULD”, and the spec should clarify that you MAY use a `.license` file with plain text files that can contain comments.

Alternatively, the RUSE Tool could be updated to give an error if it detects that a plain text file can contain comments but doesn’t contain a license header. I have two concerns with that approach:

- [Sometimes, files look like they can contain comments but actually can’t.](https://github.com/fsfe/reuse-docs/issues/82)
- [Sometimes, it’s just more convenient to use a `.license` file.](https://github.com/fsfe/reuse-tool/issues/367)

**Comment by carmenbianca** [comment]
Soft agree. Thanks for this issue.

**Comment by silverhook** [comment]
Personally, as stated in https://github.com/fsfe/reuse-docs/issues/82 , I think the Spec is OK, but not perfect in that regard.

If we change it,  I’d still prefer if the language hinted at a strong preference to having the headers in the file comments.

**Comment by Jayman2000** [comment]
> If we change it, I’d still prefer if the language hinted at a strong preference to having the headers in the file comments.

I agree. I feel like, based on RFC 2119, replacing “MUST” with “SHOULD” would indicate a strong preference to having the headers in the file comments. What do you think? Is just replacing “MUST” with “SHOULD” enough, or should additional language be added?
