### ISSUE TITLE
How to classify proprietary files

### ISSUE THREAD

**Issue by niccokunzmann** [fsfe/reuse-docs#125]
I have some files in my repository that I test against that are not FOSS. How can I correctly tell REUSE that that is the case?

At the moment, I have created a license that is not ok and added it to the file.

```
$ reuse lint

# BAD LICENSES

'AI-SPEC' found in:
* LICENSES/AI-SPEC.txt
* tests/data/grammar/header_specification_page_15.txt


# SUMMARY

* Bad licenses: AI-SPEC
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: AI-SPEC, GPL-2.0-or-later
* Read errors: 0
* Files with copyright information: 51 / 51
* Files with license information: 51 / 51

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

Do I ignore that file? I would like a proper return code `0` for lint so I can use it in CI.

So, I am looking at this: https://reuse.software/faq/#custom-license

Ok. I found it. I need to prefix it with `LicenseRef-`. That is not really clear there.
```
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: GPL-2.0-or-later, LicenseRef-AI-SPEC
* Read errors: 0
* Files with copyright information: 51 / 51
* Files with license information: 51 / 51

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```

Two issues:
- [ ] The BAD LICENSES Section should generate a link and explanation on how to create custom licenses.
- [ ] The website (tutorial and FAQ) should have a link to their source.

**Comment by mxmehl** [comment]
You solved it the right way. Thanks for providing the two tasks.

> * [ ]  The BAD LICENSES Section should generate a link and explanation on how to create custom licenses.

For this, we have https://github.com/fsfe/reuse-tool/pull/698. For the bad license, there is a link to the said FAQ item.

> * [ ]  The website (tutorial and FAQ) should have a link to their source.

That's a good point. I will create a separate issue, and close this one.
