### ISSUE TITLE
The official site currently only lists specification v3.0

### ISSUE THREAD

**Issue by ForNeVeR** [fsfe/reuse-docs#144]
I see specification v3.1 in this very repository, while specification v3.0 is currently online at https://reuse.software/spec/

I remember some story about specification being rolled back, is this related? What is the current official latest specification I should follow?

**Comment by silverhook** [comment]
We are finalising the

**Comment by ForNeVeR** [comment]
Ah, yep, that makes sense. Sorry for the fuss.
