### ISSUE TITLE
GitHub support

### ISSUE THREAD

**Issue by sdavids** [fsfe/reuse-docs#145]
It would be nice if GitHub would pickup the licenses downloaded by REUSE.

[Determining the location of your license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license)

I think you should file an issue in their support tool:

https://github.com/orgs/community/discussions/categories/repositories

**Comment by nicorikken** [comment]
This is already a longstanding issue, also linked here https://github.com/fsfe/reuse-tool/issues/901
