### ISSUE TITLE
Redefining the three steps

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#20]
Max and I are working on redefining the three REUSE steps.

The current steps are:

1. Provide the exact text of each license used
2. Include a copyright notice and license in each file
3. Provide an inventory for included software

During our sprint, we produced this:

1. Choose and provide a license
2. Add a license header to each file
3. Confirm compliance with the linter

I am not _entirely_ happy with the exact wording, but I like the gist of it.

1. "Choose and provide a license" is more succinct than the first iteration, and puts emphasis on actually choosing a license. But it does not emphasise the fact that you are very likely to have multiple licenses, at all. Is this an okay trade-off?

2. "Add a license header to each file". This is good, but I'm not sure if "license header" necessarily includes copyright tags. Is there a short synonym we can use instead? "Add a copyright and license tag to the header of each file"?

3. "Confirm compliance with the linter". This is good, but I feel that the wording is wrong. "linter" should probably be replaced by "REUSE tool". And I am not really sure on the word "compliance". Compliance is one step removed from what the developer really wants: Every file having clear copyright and licensing information.

**Comment by silverhook** [comment]
Ad 1., perhaps:

- Choose and provide the main licence for your project
- Choose a main license and provide all licenses

Ad 2., perhaps:

- Add license and copyright notice in each file
- Add license and copyright tags in the header of each file

Ad 3.:

- Confirm conformance (e.g. with the `reuse` linter tool)

Of course, these are not as nice and short as your initial suggestions.

**Comment by mxmehl** [comment]
Since we speak about the headlines, I wouldn't want to go too much into detail, but keep it short and simple.

What about:

1. Choose and provide licenses (could also be one license)
2. Add license and copyright information to each file
3. Confirm REUSE compliance

**Comment by carmenbianca** [comment]
I really like the suggestions by @mxmehl, verbatim.

**Comment by silverhook** [comment]
>     1. Choose and provide licenses (could also be one license)
>     2. Add license and copyright information to each file
>     3. Confirm REUSE compliance

LGTM +1

Good job

**Comment by carmenbianca** [comment]
Pushed fixing commits to #19 and #18 

Thanks @mxmehl
