### ISSUE TITLE
Spec: License Files must be in plain text

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#24]
As discussed https://github.com/fsfe/reuse-docs/pull/23#discussion_r287809129, if at all possible, it would be very useful to turn the suggestion for storing license texts in plaintext into a requirement.

To remind everyone, the main goal of REUSE is to make license and copyright information of source code easily parsable by both humans and machines. So having all info stored as plain text seems to be the most desirable outcome.

**Comment by carmenbianca** [comment]
I am editing the first comment here to exclude the suggestion to keep all licenses in LICENSES/. This keeps the thread focused on one topic. See #27 for the other topic. I am copying the removed text to that issue.

**Comment by carmenbianca** [comment]
My thoughts:

- I don't know any software licenses that are not available as plain-text.

- I cannot think of a reason why a non-plain-text license could not be converted to plain-text.

So the "MUST" recommendation here is probably harmless. I'm in favour.

**Comment by mxmehl** [comment]
> So the "MUST" recommendation here is probably harmless. I'm in favour.

Me too

**Comment by carmenbianca** [comment]
Added in #23
