### ISSUE TITLE
Spec: Add a statement at the start clarifying that a comment header in every file is preferable

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#25]
Thread: https://github.com/fsfe/reuse-docs/pull/23#discussion_r285212278

Relevant section:

```
This specification defines a standardized method for declaring copyright and
licensing for software projects. The goal of the specification is to have
unambiguous, machine-readable copyright and licensing information for each
individual file in a project.
```

---

@silverhook 

> Perhaps also add why we the aim is to have license info **in** _every_ file.

@carmenbianca 

> I'm sorry I don't understand well enough what you mean here.

@mxmehl 

> I think @silverhook means that there is a big benefit of having copyright information in the files, not somewhere else like a DEP-5 file, because they will retain even if just a single file is copied from a project. Right?

@silverhook 

> Yes, that’s exactly what I meant with that suggestion.

**Comment by carmenbianca** [comment]
I'm not sure if this is needed per se in the preamble of the spec. The spec itself already makes a clear recommendation of comment headers over DEP5. But here would be my suggestion:

This specification defines a standardized method for declaring copyright and
licensing for software projects. The goal of the specification is to have
unambiguous, machine-readable copyright and licensing information for each
individual file in a project. Ideally this information is embedded into every file,
so that the information is preserved when the file is copied and reused by third
parties.

**Comment by mxmehl** [comment]
LGTM, thanks!

**Comment by silverhook** [comment]
LGTM. Perhaps we should expand it to say “machine- and human-readable copyright and licensing information”.

**Comment by carmenbianca** [comment]
Added in d85fe57
