### ISSUE TITLE
Spec: Define "Project" or "Package"

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#26]
Thread: https://github.com/fsfe/reuse-docs/pull/23#discussion_r285228754

---

@silverhook 

> Defining this is a tough one, as in the (free) software world a “project” is quite different than what a project is in more traditional contexts. Would warmly recommend someone else to take a look as well. I remember @ohnewein pointing this out before, so he might have a good idea.
> 
> Perhaps something in the lines of:
> 
> ```
> - Project --- A repository or archive of source code, ………
> ```
> 
> …or we just skip the definition and rely on the fact that a “open source project” as an established term in the business.

@carmenbianca 

> I don't think we can skip defining that, because it's such a central term.
> 
> "Project" is the only word I know for "the directory containing all the source files for a given program".

@goneall

> In SPDX we use the term package for describing a set of files related to a distribution. This would include the source files for a given program but could also include other related files.

@silverhook 

> Package may indeed be more accurate. Especially, if we could piggy-back on SPDX Spec here. @goneall, I can’t find where “Package” itself (as opposed to “Package Information”, “Package Name”, “Package Version”, etc.) is specified in SPDX Spec though. Am I missing something?

@goneall

> I also looked for a definition in the spec and did not see a concise definition of a package. I do recall discussing this at length during the spec development. Something we may want to add to the spec.

@silverhook 

> in that case, I think it would be best if both projects use the same definition, until SPDX adopts it in a published spec. Then REUSE can simply refer to that definition.

**Comment by carmenbianca** [comment]
https://github.com/spdx/spdx-spec/issues/125

**Comment by silverhook** [comment]
https://github.com/spdx/spdx-spec/pull/129 (i.e. the pull request solving 125) looks very usable to me. Great work everyone.

**Comment by carmenbianca** [comment]
Used the SPDX definition in 687353e
