### ISSUE TITLE
Spec: Define copyright notice prefixes

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#28]
Threads:

https://github.com/fsfe/reuse-docs/pull/23#discussion_r285257688

https://github.com/fsfe/reuse-docs/pull/23#discussion_r285268959

https://github.com/spdx/spdx-spec/issues/122

The gist of it is this:

We should mandate usage of the SPDX-Copyright tag and/or the © symbol.

@silverhook @mxmehl @carmenbianca

**Comment by mxmehl** [comment]
I'd be fine with either SPDX-Copyright or ©. Both wouldn't be doable I am afraid.

Let's see what comes out of it during the feedback phase.

**Comment by carmenbianca** [comment]
These notices are currently valid under the proposed spec:

```                                                                             
SPDX-Copyright: 2019 Jane Doe <jane@example.com>                                
SPDX-Copyright: © 2019 John Doe <joe@example.com>                               
© Example Corporation <https://corp.example.com>                                
Copyright 2016, 2018-2019 Joe Anybody                                           
Copyright (c) Alice                                                             
```

The idea is:

1. SPDX-Copyright is recommended.

2. Adding the © symbol after the `SPDX-Copyright` tag is supported-but-not-mandated for people who really want/need that symbol.

3. Existing conventions are supported-but-not-recommended.

I would _like_ to remove the third item and mandate the usage of `SPDX-Copyright`, but that would instantly make REUSE incompatible with the Linux kernel and a sensible existing convention.

The second item does not bother me much.

**Comment by mxmehl** [comment]
Fine for me!

**Comment by carmenbianca** [comment]
I have sent [a message to spdx-legal](https://lists.spdx.org/g/Spdx-legal/message/2602). We'll see what happens :)

**Comment by silverhook** [comment]
I see this closed, but how about a status update? :)

**Comment by mxmehl** [comment]
It is in the [2.2 milestone of spdx-spec](https://github.com/spdx/spdx-spec/milestone/2) which is said to be due Nov/Dec 2019. That's too long for us. Since we only make a (very sane) recommendation, we thought that it's fine to make a step forward now.

Since REUSE 3.0 will be up for discussion soon, we assume there will be feedback about this as well. So let's see how people think about it then.
