### ISSUE TITLE
Spec: How to do multiple licenses without "AND" in DEP5

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#31]
Thread: https://github.com/fsfe/reuse-docs/pull/23#discussion_r285262612

Also https://github.com/spdx/spdx-spec/issues/123

---

@silverhook 

> DEP5 does make use both of `and` and `or` as well as brackets `(` and `)` for grouping – identical to SPDX syntax.
> 
> There are some other incompatibilities between DEP5 and SPDX though, mainly in the names of some of the licenses:
> https://wiki.debian.org/Proposals/CopyrightFormat#Differences_between_DEP5_and_SPDX

@carmenbianca 

> > I know, but I'm trying to do the following:
> 
> ```
> SPDX-License-Identifier: MIT
> SPDX-License-Identifier: 0BSD
> ```
> 
> This is different from `MIT AND 0BSD` and `MIT OR 0BSD`. It means that part of the file is under MIT, and part is under 0BSD.
> 
> `MIT AND 0BSD` suggests that both licenses apply to the contents of the file and that they must both be obeyed, which is really really close.
> 
> `MIT OR 0BSD` suggests that the user may choose which license applies to them, which is not correct.

@carmenbianca 

> Oh, as addendum, another way that the SPDX spec deals with this is:
> 
> ```
> SPDX-License-Identifier: MIT; 0BSD
> ```
> 
> (but the tool currently does not support this :x)

@goneall

> Could you just list separate licenses on separate SPDX-License-Identifier lines as described above? In converting to an SPDX document, the tools which parse the source files would need to convert them to an expression for the file declared license, but it could also add them individually to the `PackageLicenseInfoFromFiles` which is a list of licenses collected from the source files.

@carmenbianca 

> That's what we normally do in source code files, but that isn't supported inside of the DEP5 spec, that I know of.
> 
> It's a bit of a pedantic thing, though, because the operators `AND` and `;` are _almost_ identical.

@carmenbianca 

> Coming back to this: I suggested that the SPDX spec allows an expression such as
> 
> ```
> SPDX-License-Identifier: MIT; 0BSD
> ```
> 
> This is false. I researched this further today, and could not find it in the spec. Instead, I had previously found it [here](https://wiki.spdx.org/view/FileNoticeExamples#Package_Examples), but had not read the disclaimer that the spec does not (yet?) support this.

@goneall

> I can confirm that most license expression parsers don't support this operator.
> 
> In any case, I would recommend not using the `;` as most SPDX license expression parsers will fail and there is no agreed to definition in the SPDX spec.
> 
> I added an issue to the SPDX Spec to track either adding to to the spec or removing it from the wiki page to avoid future confusion: [spdx/spdx-spec#123](https://github.com/spdx/spdx-spec/issues/123)

@silverhook 

> I think you are either _a)_ over-thinking it on the file-level, or _b)_ are going into the direction where we need to figure out how to handle things on the snippet-level.
> 
> On the **file-level**, I think interpreting:
> 
> ```ini
> SPDX-License-Identifier: MIT
> SPDX-License-Identifier: 0BSD
> ```
> 
> should be simply `MIT AND 0BSD`, as to use that _file_ you do need to comply with both licenses at the same time anyway. If you can’t easily and predictably figure out which snippet is under the other license, it’s pointless to point out the difference.
> 
> If you want to expand REUSE to include recommendations on **how to properly tag code snippets** of a different license than the main license of the file, I’m all for that and happy to help. But this will be more complex. It may very well be worth it, as SPDX also already supports snippet-level licensing, as do some tools already.
> 
> But doing something in between the two I think is complicating too much for too little gain. Let’s either not complicate needlessly, or complicate for actual gain.

**Comment by carmenbianca** [comment]
I don't think there's a satisfying solution to this. However, because DEP5 is optional, they can just use regular headers if DEP5 doesn't work for them.

Problem solved?

**Comment by silverhook** [comment]
I still don’t see the problem in the first place. DEP5 allows for `AND` and `OR` just as SPDX does. Both can go down to the file level.

It is only at snippet level that you will come to this issue. DEP5 does not go that deep, so on a file level you would need to resort to `LicenseA AND LicenseB`, as both need to be followed in that file.

If we want to figure out how to store snippet-level licensing (and copyright) info in REUSE, I’m game. That would also be a great use for tools to come

**Comment by carmenbianca** [comment]
Snippets are probably a good idea for a 4.0 version of the spec.

**Comment by silverhook** [comment]
I very much agree with closing this as outside of scope of REUSE 3.0 and putting snippet-level markup on the 4.0 Roadmap

**Comment by mxmehl** [comment]
Sounds sensible. So let's close this :)
