### ISSUE TITLE
FAQ: Explain how to do custom exceptions

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#32]
Thread: https://github.com/fsfe/reuse-docs/pull/23#discussion_r287842767

Suggested addition:

> In the exceptional case you absolutely need to use a license exception that does not exist in the SPDX License List, you MUST instead include the exception text in the License File of the license the exception relates to and you MUST name that License File appropriately. I.e. its SPDX Identifier MUST be `LicenseRef-[idstring]`, as defined by the SPDX Specification, where `[idstring]` MUST indicate that it is a custom license or that there it includes custom exception. Examples: `LicenseRef-ProjectX-Community-License`, `LicenseRef-GPL-2.0-only-with-ProjectX-exception`.

@silverhook @goneall @carmenbianca

**Comment by carmenbianca** [comment]
I think we can put this in the FAQ instead of the spec. It's an uncommon scenario that someone could also figure out by themselves given the restrictions of the spec. e.g., "if I can't create a custom exception, then I'll just create a custom license".

**Comment by silverhook** [comment]
I’m OK with putting it in the FAQ. But we should make sure that the FAQ is not in conflict with the Spec.

It seems to me that the current WIP version of the Spec (i.e. at ccc7a7b4ce96d882651bf81fcec160ba3021bdb4) would allow for such an FAQ entry. So that should be fine +1

**Comment by carmenbianca** [comment]
Added in 091bc4f
