### ISSUE TITLE
Spec: How to mark snippets

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#34]
Copied code can also be in the form of smaller snippets, not just whole files. In order to track that code, we need to be able to mark the snippet of code so both a human and machine can very easily tell where the snippets begins, ends, and which license/copyright info applies to it.

Overview of how fine-grained the license and copyright info each solution can store:

- SPDX can handle handle package, file, and snippet level
- Debian DEP5 can handle package, and file level
- REUSE 1.x-3.x can handle package, and file level

See also #31 and links in it.

**Comment by silverhook** [comment]
An idea to kick-start the discussion:

```python
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-Copyright: © 2019 Contributors to projectA <https://proejectA.example>

import quasicode

for i in range(1-10):
[…]

# REUSE-Snippet-Begin
# SPDX-License-Identifier: MIT
# SPDX-Copyright: © 1978 Lone Hacker <l@hacker.example>

if user.hook = true:
    print("yay")
[…]
# REUSE-Snippet-End

while true = true:
    do magic
[…]

return 1
```

To avoid an issue with nesting, we might need to add unique identifiers to `REUSE-Snippet-*` tags – e.g.:
- `REUSE-Snippet-Begin-lone-code` and `REUSE-Snippet-End-lone-code`; or
- `REUSE-Snippet-Begin-eb139` and `REUSE-Snippet-End-eb139`

As SPDX is the only solution currently able to handle this on a snippet-level, it would make sense to see if we can borrow tags and ideas from their spec.

**Comment by silverhook** [comment]
We have tried this idea in one of Liferay’s projects:

https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_print.scss

https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_reboot.scss

https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_utilities-functional-important.scss#L191

**Comment by mxmehl** [comment]
See the thread I've started at SPDX: https://lists.spdx.org/g/Spdx-legal/topic/74693470#2851

Also the discussion on the REUSE ML: https://lists.fsfe.org/pipermail/reuse/2020q1/000051.html

**Comment by silverhook** [comment]
Snippets in source code have been accepted into SPDX (2.3) with https://github.com/spdx/spdx-spec/pull/719 as part of the [Annex H Specifying SPDX information in source files (Informative)](https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/file-tags.md)

I will draft the wording for REUSE.
