### ISSUE TITLE
Tutorial: Split off tutorials for specific/advanced use cases

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#38]
To keep the Tutorial simple to understand and follow, it would make sense to limit it to the basic/standard use case.

It would make sense to write short tutorials (or FAQ entries) for specific and advanced use cases.

Thoughts? Suggestions on what to include there (and perhaps remove from the main Tutorial)?

**Comment by mxmehl** [comment]
That's how @carmenbianca and I planned it. The FAQ answers much more complex issues and edge cases than the tutorial, and at the same times skips quite some basic reasoning.

Do you see parts of the tutorial which are not relevant for 90% of small to medium-sized projects?

**Comment by arcturus140** [comment]
Are you referring to the [reuse-example](https://github.com/fsfe/reuse-example)?

I think that it is simple to understand and covers 90%+ of small to medium-sized projects.

**Comment by carmenbianca** [comment]
Referring to https://github.com/fsfe/reuse-docs/pull/19

**Comment by mxmehl** [comment]
> Are you referring to the [reuse-example](https://github.com/fsfe/reuse-example)?
> 
> I think that it is simple to understand and covers 90%+ of small to medium-sized projects.

Yes exactly. Together with the tutorial text which Carmen linked, this is planned to explain the most important basics. If not, we have to change it!

**Comment by mxmehl** [comment]
Closing this issue since we seem to have achieved this split. If not, please open a new issue explaining in detail where we currently fail to do so.
