### ISSUE TITLE
Before release of 3.0 Spec and Tutorial, make sure the `reuse lint` tool works correctly

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#39]
Before we release REUSE 3.0, the `reuse` tool needs to:

- [x] actually enforce REUSE 3.0 Spec
- [x] the above version needs to be updated on PyPI (i.e. installable by `pip`)

**Comment by carmenbianca** [comment]
The master branch of the tool currently checks the whole of the REUSE spec, except the format of copyright statements. It just checks that it starts with `SPDX-Copyright`, `©`, or `Copyright` and accepts anything following it.

I intend to release the tool in tandem with the spec, unless you see a good reason to upload it to PyPI earlier.

**Comment by silverhook** [comment]
I suspected you have an eye on it. Just wanted to make sure we don’t forget :)

**Comment by mxmehl** [comment]
Definitely! Before that, and as soon as we have the open questions resolved on our end, we should also ask for feedback of relevant stakeholders ;)
