### ISSUE TITLE
Change exception identifier to avoid confusion with SPDX spec

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#4]
REUSE specs 2.0 currently refers to the following tags:

- `Valid-License-Identifier` to tag the actual *text of* a license (and `License-Text` to include a copy of its text)
- `SPDX-Exception-Identifier` to tag the actual *text of* an exception (and `Exception-Text` to include a copy of its text)

While the license identifier tag was already changed in order not to clash with the SPDX spec’s own tags, the exception tag was not updated to match it. This can cause confusion.

I would suggest that we also change the license exception tag from `SPDX-Exception-Identifier` to `Valid-Exception-Identifier`.

For more info, see [discussion on SPDX Legal mailing list](https://lists.spdx.org/g/Spdx-legal/topic/change_use_of_spdx/24005641?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,24005641).

**Comment by mxmehl** [comment]
Is this solved in REUSE 3.0?

**Comment by carmenbianca** [comment]
No longer relevant in REUSE 3.0
