### ISSUE TITLE
Language around copyright holders should be adjusted for public domain works

### ISSUE THREAD

**Issue by LynnKirby** [fsfe/reuse-docs#46]
References to the text of `SPDX-Copyright` and copyright notices specifically refer to the "copyright holder". This can be confusing if you're using CC0 or another public domain-equivalent license.

This came up on the Debian mailing list as well. As recorded in the [Debian Wiki](https://wiki.debian.org/DFSGLicenses):

> **Q:** Public Domain in debian/copyright files? Example:
> ```
> Copyright: John Doe
> License: public-domain
> ```
>
> These two statements seems to contradict each other: public domain means exactly the _absence_ of copyright.
>
> **A:** The Copyright: field in this case is usually indicating who holds any residual copyright or author's rights in a jurisdiction which does not completely support public domain (PD). It also indicates who the individual was who dedicated the work to the PD.

If this matches the intent of the `SPDX-Copyright` tag, then the FAQ should have a similar entry and the spec should clarify that "copyright holder" also refers to the person who applied the public domain dedication to their copyrighted work.

**Comment by carmenbianca** [comment]
> If this matches the intent of the SPDX-Copyright tag, then the FAQ should have a similar entry and the spec should clarify that "copyright holder" also refers to the person who applied the public domain dedication to their copyrighted work.

This seems quite doable. But I'm wondering if this could be worded cleanly without going too deep into corner cases. Not all jurisdictions have a public domain or allow authors to commit their works to it. Therefore, in those jurisdictions, the author is still the copyright holder.

This is made more complicated by the fact that SPDX does not have a plain public domain dedication. There is CC0, Unlicense, and ODC PDDL, but no license identifier that communicates "public domain" exclusively.

**Comment by matkoniecz** [comment]
For real example - how https://commons.wikimedia.org/wiki/File:US_Navy_110831-N-NT881-079_Sailors_assigned_to_the_guided-missile_submarine_USS_Ohio_(SSGN_726)_and_Navy_Operational_Support_Center_Cincinnati_part.jpg should be specified? `CC0-1.0` is not really correct, but specifying true "Public domain" is against specification.

**Comment by LynnKirby** [comment]
@matkoniecz you can indicate any legal status using a custom license with an identifier starting with `LicenseRef-`.

**Comment by matkoniecz** [comment]
>  you can indicate any legal status using a custom license with an identifier starting with LicenseRef-.

What is the recommended licence text for public domain works? It seems to be required by

> How do I use a license that is not on the SPDX License List?

> If you have a custom or modified license that does not appear in the SPDX License List, place your license in the file LICENSES/LicenseRef-MyLicense.txt. By naming your license as such, tools that speak SPDX will still be able to recognise your license.

from https://reuse.software/faq/

And still, it seems that a standard way to indicate a PD status would be useful to avoid multiple conflicting ways of declaring the same thing.

**Comment by LynnKirby** [comment]
> What is the recommended licence text for public domain works?

REUSE recommends applying `CC0-1.0` to your own works if you want to ensure they are public domain. Otherwise you need a custom license text indicating what the legal status is. For example, the photo released by the US Navy that you previously linked could say something like "This is a work of the U.S. Government and is not subject to copyright protection in the United States. Foreign copyrights may apply."

> And still, it seems that a standard way to indicate a PD status would be useful to avoid multiple conflicting ways of declaring the same thing. 

Copyright law is too complicated to make this possible for most of the intended use cases of a public domain identifier. [See these comments by the SPDX Workgroup's legal team](https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files).

**Comment by matkoniecz** [comment]
> Some commonly used “Public Domain dedications” have already been included in the SPDX License List (e.g., ANTLR, Sax, CC-0), and others may be added to the List using the Process for Requesting New Licenses be Added.

It seems to me that "Work of US federal government" (equivalent of https://commons.wikimedia.org/wiki/Template:PD-USGov ) would be a new useful SPDX identifier. For now it seems that I need to roll my own equivalent.

**Comment by silverhook** [comment]
@matkoniecz If you want to have it added to SPDX License List, you can read about the process to do so here: https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md

**Comment by mxmehl** [comment]
If your public domain license is not on SPDX, you can add it as a [custom license](https://reuse.software/faq/#custom-license). I am not sure what else we can offer here.

Closing for now.
