### ISSUE TITLE
FAQ: handle license text templates like BSD/MIT

### ISSUE THREAD

**Issue by smcv** [fsfe/reuse-docs#48]
The FAQ says:

> Some licenses, such as MIT and the BSD family of licenses, have a line that says “Copyright © [year] [copyright holder]“. Please see **this question** about how to deal with those licenses.

where "this question" is a broken link to https://reuse.software/faq/#mit-bsd, an unanswered question that was commented out in commit eecb5ac5.

**Comment by silverhook** [comment]
Good catch. Thanks.

@carmenbianca, happy to work together on drafting an answer to that next month.

**Comment by mxmehl** [comment]
In a recent discussion, we've come to a preliminary conclusion how REUSE should deal with licenses like MIT that provide a template for someone to fill in copyright holder, year etc.

* For new REUSE users, we recommend not to fill the template. Just download the license text and provide your copyright info like with any other license
* For reused code under these licenses, out practical suggestion is to use the standard license text and take care that the original copyright holder is mentioned in the REUSE-style in the corresponding source code files
* If someone really wants to be sure, the safe way would be to add these licenses as custom licenses with `LicenseRef`, so for instance for Bootstrap: `LicenseRef-MIT-Twitter`. We should explain the practical downsides of this option though.
* Explain all of this in a FAQ entry, e.g. "How do I deal with license texts that contain copyright statements (e.g. MIT/BSD)?". We should make clear that this is no legal advice though.

**Comment by silverhook** [comment]
IIRC there is not issue with the 3.0 spec as things stand, but has anyone double-checked?

Love that this is getting fixed though! :D

**Comment by smcv** [comment]
> IIRC there is not issue with the 3.0 spec

I think this is still a valid open issue. There does not seem to be any text in the REUSE 3.0 spec about how to handle something that's under a license consisting of (for example) a BSD license, with the replaceable text filled in differently.

For example, imagine some of the source files in my project start with a license grant similar to https://spdx.org/licenses/BSD-3-Clause.html, but instead of *THE COPYRIGHT HOLDERS AND CONTRIBUTORS* it says *THE ACME CORPORATION AND ITS CONTRIBUTORS*. If I want to replace the text of the license grant with `SPDX-License-Identifier: BSD-3-Clause` to reduce the amount of boilerplate, I can't, because I'd be losing information (and arguably violating the license, because I'm no longer including "the following disclaimer" verbatim).

#51 removed the text with the broken link, but didn't answer the question.

**Comment by silverhook** [comment]
I agree, this is still not fixed, but I’m just saying I don’t see a conflict with the *spec* if we do it as @mxmehl said, so it can be just done as a clarification. I would need to re-read the spec to make sure though.
