### ISSUE TITLE
add comparison with similar projects

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-docs#53]
I am currently starting a project where machine readable licensing info would be useful. It would be useful to have somewhere overview of alternative projects, with comparison of differences.

I found https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ (has useful examples at the end). Are there any other similar projects?

**Comment by mxmehl** [comment]
It's only a rough page, but does https://reuse.software/comparison deliver what you seek for?

**Comment by matkoniecz** [comment]
Yes.
