### ISSUE TITLE
what is the standard way of providing source of file

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-docs#54]
In my specific case I want to (as mandatory) specify author and the licence.

But I also want to specify that file (image in this case) is from https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/bunker.svg

What is the standard tag name for that?

**Comment by carmenbianca** [comment]
https://spdx.org/spdx-specification-21-web-version#h.3ygebqi

`SPDX-FileComment:`, probably. `SPDX-PackageDownloadLocation:` is also a candidate, but applies to packages rather than files.

Perhaps it's a good question to ask upstream at SPDX? https://github.com/spdx/spdx-spec

**Comment by mxmehl** [comment]
There has been a discussion about that on the SPDX legal mailing list: https://lists.spdx.org/g/Spdx-legal/topic/32590067

Since it's clearly an SPDX issue and not in the scope of REUSE, I'll close here :)
