### ISSUE TITLE
Third-party "uncopyrightable" or public domain works

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#58]
@mxmehl linked to this answer earlier today in a discussion thread: https://reuse.software/faq/#uncopyrightable

The answer tells you how to deal with your own uncopyrightable files. It does not tell you how to deal with the uncopyrightable files of other people. Maybe it should also do that.

Dealing with public domain works of others (i.e., "this file is in the public domain") should also be addressed. Can you simply slap `CC0-1.0` on these files? @silverhook

**Comment by silverhook** [comment]
> Dealing with public domain works of others (i.e., "this file is in the public domain") should also be addressed. Can you simply slap CC0-1.0 on these files? @silverhook

No, it’s not up to you to do that.

I would say you need to find the public domain dedication/license text that that code’s author used to indicate they want to release that to the public domain, and store that in `LICENSES/` – if it’s a standard one, just use its SPDX ID, if it’s not, copy-paste it into e.g. `LICENSES/LicenseRef-public_domain_component_or_author_X.txt`

**Comment by mxmehl** [comment]
I am not sure what else we can say except what we already do:

> It is important to note that you can only do this for your own works. If the file was authored by someone else, you must declare their copyright and license in the header.
