### ISSUE TITLE
Clarify that the upstream accepting contributions is actually on GitHub (and git.fsfe.org is just a mirror)

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#6]
Currently the README says that the repository to contribute to is on git.fsfe.org. After speaking with @jonasob , it seems that the opposite is the case and that git.fsfe.org should be just a mirror.

In that case let’s clarify this in the README.

(Alternatively, let’s move all issues to git.fsfe.org from here.)

**Comment by mxmehl** [comment]
The README should be clear in this regard now.
