### ISSUE TITLE
Improving the FAQ for adding copyright and licensing information

### ISSUE THREAD

**Issue by lucaslasota** [fsfe/reuse-docs#65]
Hello,

in the REUSE tutorial[1] it is well explained how to add the comment headers. It lacks however the information about the extension of the LICENSE file. it could be helpful to add language or an example for the .txt suffix, for example:

`*<SPDX-ID>.txt`
`* LicenseRef-<name>.txt` (for licenses that are not in the SPDX list)[2]

Thanks!

[1] https://reuse.software/tutorial/#step-1
[2] https://reuse.software/faq/#custom-license

**Comment by mxmehl** [comment]
I am working on improving the custom-license section, and #69 will track this specifically. Also, #57 will deal with "tradition", so continuing to use LICENSE files.
