### ISSUE TITLE
Add custom licence identifier usage to FAQ answer

### ISSUE THREAD

**Issue by uiopaubo** [fsfe/reuse-docs#69]
In the FAQ answer providing instructions on employing a custom licence...

https://reuse.software/faq/#custom-license

...it might be worthwhile to provide an example that uses the custom licence identifier, just to remove any doubt about the exact form it takes. The example licence filename...

LICENSES/LicenseRef-MyLicense.txt

...corresponds to the identifier LicenseRef-MyLicense. Given the usual translation of identifiers to filenames, one might have expected the identifier to be this (merely removing the extension), but as the edit history to this comment can attest, it is easy to think that the identifier might just be MyLicense. So there is potential for some confusion.

**Comment by silverhook** [comment]
It *does* correspond to the SPDX Identifier `LicenseRef-MyLicense`.

To clarify, the header:

```
# SPDX-FileCopyrightText: 2020 Doood <d00d@example.org>
#
# SPDX-License-Identifier: LicenseRef-DooodsLicense
```

means the license is to be found in `LICENSES/LicenseRef-DooodsLicense.txt`

I agree that it might be useful to state that explicitly in the FAQ.
