### ISSUE TITLE
Specify the format of `.license` files

### ISSUE THREAD

**Issue by kirelagin** [fsfe/reuse-docs#73]
Currently the spec only says:

> an adjacent file of the same name with the additional extension `.license`

In other words, it only specifies the name of the file, but does not _clearly_ specify the contents.

Therefore, I propose to:

1. State that this has to be a _text_ file. (For context, POSIX defines [what a text file is][posix:textfile]; related: fsfe/reuse-tool#187).
2. Require it to be encoded as UTF-8 (This one is tricky, but, trust me, this needs to be done (for context, there is a [fantastic blog post that explains the issue][serokell:utf8] although in the context of Haskell, but the general principles are the same); related: fsfe/reuse-tool#221).

[posix:textfile]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403
[serokell:utf8]: https://serokell.io/blog/haskell-with-utf8

**Comment by kirelagin** [comment]
The simplest possible change would be to `s/an adjacent file/an adjacent UTF-8-encoded text file/`, however it might be worth it to make this even more explicit and split into a separate sentence or something.

**Comment by silverhook** [comment]
A problem I see with making this a requirement is places where UTF is not an option.

For example, already if you look at the Linux kernel source code, it is encoded in ASCII. I suspect other software that is aimed to be embedded in hardware will have a similar limitation.

I do think we should at least encourage UTF. How about adding `That file SHOULD be UTF-8-encoded.` instead? So a (hard) suggestion, but not a requirement.

**Comment by smcv** [comment]
> For example, already if you look at the Linux kernel source code, it is encoded in ASCII

UTF-8 is an ASCII-compatible encoding (a superset of ASCII where every byte value that is allowed in ASCII means the same thing in UTF-8), so every ASCII text file is automatically a valid UTF-8 text file.

**Comment by silverhook** [comment]
> UTF-8 is an ASCII-compatible encoding (a superset of ASCII where every byte value that is allowed in ASCII means the same thing in UTF-8), so every ASCII text file is automatically a valid UTF-8 text file.

True, and that is a great feature of Unicode encodings :)

**Comment by smcv** [comment]
> True, and that is a great feature of Unicode encodings :)

Not Unicode encodings in general, just UTF-8. UTF-16, UCS-2 and UCS-4 are not ASCII supersets.
