### ISSUE TITLE
Refine how documentation licensing should be done

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-docs#8]
Around the middle of §2 or REUSE spec 2.0 one can find the following text:

> If your project includes documentation which is not included in the final build artefact, you are encouraged but not obliged to include license information for these too.

… but then does not go into any detail on how to do that or what that documentation is. It would make sense to expand on this.

# Assuming the documentation is not in the code base

Should the license info for documentation be stored in the code base? Problem: how to associate it with the documentation? Perhaps with a URL and [SPDX ID](https://spdx.org/ids)? This sounds suboptimal (URLs can change, content move) and may cause false positives esp. with license scanning tools.

Should the license info for documentation be stored in the documentation? If so, how? Just an SPDX ID preferably in plain text (in the footer)?

# Assuming the documentation is in the code base, but excluded from the build

I suspect applying the same rules as in §1 and §2 of REUSE spec 2.0 should be fine here.

But if that is the case, it would be would be good to clarify that this assumption is what is meant (and not the assumption above it).

**Comment by mxmehl** [comment]
Is this still a problem in spec 3.0?

**Comment by silverhook** [comment]
I think in 3.0 spec this got solved in the general clean-up. Closing
