### ISSUE TITLE
Update to SPDX 2.2

### ISSUE THREAD

**Issue by Jayman2000** [fsfe/reuse-docs#83]
At the moment, the REUSE Spec uses version 2.1 of the SPDX Spec, but version 2.2 is available.

**Comment by silverhook** [comment]
Knowing SDPX’ process, I don’t expect anything to break with a spec update.

If nothing else, it makes sense to update to newer SPDX Spec, to also inherit the newer SPDX License List and their IDs.

**Comment by mxmehl** [comment]
Please also see fsfe/reuse-tool#394
