### ISSUE TITLE
Questions about the release date of REUSE.yaml

### ISSUE THREAD

**Issue by dd-jy** [fsfe/reuse-docs#91]
Hi,
I am very interested in REUSE.yaml(https://github.com/spdx/spdx-spec/issues/502).
May I know the approximate release date of the REUSE.yaml?
And  also I wonder when the official name and specification for REUSE.yaml will be decided.

**Comment by carmenbianca** [comment]
We're doing a hackathon this month. I doubt we'll have a release estimate, but if nothing goes wrong a lot of progress will be made this January.

**Comment by dd-jy** [comment]
Thank you for the very quick response!
I'm looking forward to it! 😃

**Comment by mxmehl** [comment]
This unfortunately also depends on the progress at SPDX. The actual implementation in REUSE is not trivial but doable, but we'd like to wait for SPDX to officially merge this into their spec.

Rationale: being compliant with the SPDX spec means that users implementing REUSE.yaml also benefit from compatability with other best practices and compliance tools, e.g. better rating at ClearlyDefined. This is to reduce doubled work for users or even conflicting best practices.
